### PR TITLE
Adding organization, modern patterns, styles and more functionality

### PR DESCRIPTION
**Pull request by erikfritas**
Congratulations on the good work of your team, I hope you enjoyed this contribution...

### CODE REVIEW

**Comment by erikfritas** [comment]
I removed the .DS_Store file from the project

**Comment by sabahzero** [comment]
Hi @erikfritas, thank you for this thoughtful contribution! It looks like there may now be some bugs with [the site](https://ivamp-consortium.github.io/) as a result of the merge. I'll give about 10 minutes or so to update and check back, otherwise will go back to original version. I used .gitignore to have the .DS_Store file there but not included (since I have a MacOS and it does this each time)

**Comment by erikfritas** [comment]
do you want the .DS_Store file there?

**Comment by erikfritas** [comment]
what bug did you find there?

**Comment by erikfritas** [comment]
can i try to fix?

**Comment by sabahzero** [comment]
Ah, it looks like it rendered. Thank you, looks beautiful!

If you'd like to attempt either of these issues, feel free:
https://github.com/ivamp-consortium/ivamp-consortium.github.io/issues

**Comment by erikfritas** [comment]
thank you very much for your attention 😃

**Pull request merged**
